Repository cevi/automatic_walk-time_tables, pull requests merged in 2022-11, with the labels that each got.

#124 Add names to volumes
  docker-compose.yml
Labels: Release 3.0.0

#125 Fix line endings #123
  webinterface/package.json
Labels: Release 3.0.0

#135 Introduces e2e Tests with Cypress
  .env.ci-testing
  .github/workflows/cypress.yml
  Readme.md
  backend/automatic_walk_time_tables/generator.py
  docker-compose.ci-testing.yml
  docker-compose.yml
  docs/.vitepress/config.js
  docs/documentation/introduction/environment.md
  docs/documentation/introduction/testing.md
  e2e/.gitignore
  e2e/Dockerfile
  e2e/cypress.config.js
  e2e/cypress/.gitignore
  e2e/cypress/e2e/gpx.cy.js
  e2e/cypress/e2e/interactive_GPX.cy.js
  e2e/cypress/e2e/kml.cy.js
  e2e/cypress/e2e/utils.js
  e2e/cypress/fixtures/Hofstetten_Schauenberg.gpx
  e2e/cypress/fixtures/Linthal_Limmernsee_Brigels.gpx
  e2e/cypress/fixtures/Nesslau_Speer_Amden.gpx
  e2e/cypress/fixtures/Seebach_Steinmaur.gpx
  e2e/cypress/fixtures/Taminaschlucht.gpx
  e2e/cypress/fixtures/Thusis_Tiefencastel.gpx
  e2e/cypress/fixtures/Wald_Steg.gpx
  e2e/cypress/fixtures/Wyssachen_Napf_Luthern.gpx
  e2e/cypress/fixtures/app_extralong.gpx
  e2e/cypress/fixtures/app_extrashort.kml
  e2e/cypress/fixtures/map_many.kml
  e2e/cypress/fixtures/map_short.kml
  e2e/cypress/fixtures/map_three_lines.kml
  e2e/cypress/fixtures/map_two_lines.kml
  e2e/cypress/fixtures/outdooractive_loop.gpx
  e2e/cypress/fixtures/outdooractive_medium.gpx
  e2e/cypress/fixtures/outdooractive_short.gpx
  e2e/cypress/fixtures/test_small.gpx
  e2e/cypress/fixtures/test_small.kml
  e2e/cypress/fixtures/unsupported/map_detour.kml
  e2e/cypress/fixtures/unsupported/map_loop.kml
  e2e/cypress/fixtures/unsupported/map_real.kml
  e2e/cypress/support/commands.js
  e2e/cypress/support/e2e.js
  e2e/package-lock.json
  e2e/package.json
  frontend/angular.json
  frontend/package.json
  frontend/src/app/pages/download-data/download-data.component.ts
  frontend/src/app/pages/download-pending/download-pending.component.html
  frontend/src/app/pages/export-settings/export-settings.component.html
  frontend/src/app/pages/export-settings/export-settings.component.ts
  frontend/src/app/services/map-animator.service.ts
  swiss_TLM_api/app.py
Labels: ci, Release 3.0.0

#155 Fix/add back tile cache
  backend/automatic_walk_time_tables/map_downloader/create_map.py
  docker-compose.yml
  mapfish_print_server/swisstopo_config/config.yaml
  tile_caching/.gitignore
  tile_caching/Dockerfile
  tile_caching/nginx.conf
Labels: enhancement, backend
